apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  labels:
    app: minio
    component: init
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: minio
        component: init
    spec:
      restartPolicy: OnFailure
      initContainers:
      # Wait for MinIO to be ready
      - name: wait-for-minio
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Waiting for MinIO to be ready..."
          until nc -z minio 9000; do
            echo "MinIO not ready yet, waiting..."
            sleep 5
          done
          echo "MinIO is ready!"
          sleep 10
      containers:
      - name: init-minio
        image: quay.io/minio/mc:latest
        env:
        - name: MC_CONFIG_DIR
          value: /tmp/.mc
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PASSWORD
        command:
        - sh
        - -c
        - |
          #!/bin/sh
          set -e

          echo "========================================"
          echo "MinIO Initialization Job"
          echo "========================================"
          echo ""

          # Configure mc alias
          echo "Configuring MinIO client..."
          mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD

          echo "✓ MinIO client configured"
          echo ""

          # Create buckets
          echo "Creating buckets..."

          if mc ls myminio/models >/dev/null 2>&1; then
            echo "✓ Bucket 'models' already exists"
          else
            mc mb myminio/models
            echo "✓ Created bucket 'models'"
          fi

          if mc ls myminio/train-detections >/dev/null 2>&1; then
            echo "✓ Bucket 'train-detections' already exists"
          else
            mc mb myminio/train-detections
            echo "✓ Created bucket 'train-detections'"
          fi

          echo ""

          # Create model directory structure and config.pbtxt
          echo "Creating model structure..."

          # Create config.pbtxt in /tmp
          cat > /tmp/config.pbtxt << 'EOF'
          name: "yolo11n"
          backend: "onnxruntime"
          max_batch_size: 0
          EOF

          # Upload config.pbtxt to correct path for KServe
          # InferenceService storageUri: s3://models/model downloads to /mnt/models/
          # Triton needs: /mnt/models/yolo11n/config.pbtxt
          mc cp /tmp/config.pbtxt myminio/models/model/yolo11n/config.pbtxt
          echo "✓ Created models/model/yolo11n/config.pbtxt"

          # Download and upload YOLO model from GitHub
          echo ""
          echo "Downloading YOLO model from GitHub..."

          GITHUB_RAW_URL="https://raw.githubusercontent.com/mouachan/train-occupancy-detection/main/models/yolo11n.onnx"

          # Download using curl (more commonly available than wget)
          if curl -f -L -o /tmp/model.onnx "$GITHUB_RAW_URL" 2>/dev/null; then
            if [ -f /tmp/model.onnx ] && [ -s /tmp/model.onnx ]; then
              echo "✓ Model downloaded successfully ($(du -h /tmp/model.onnx | cut -f1))"

              # Upload to MinIO
              echo "Uploading model to MinIO..."
              mc cp /tmp/model.onnx myminio/models/model/yolo11n/1/model.onnx
              echo "✓ Model uploaded to models/model/yolo11n/1/model.onnx"
            else
              echo "⚠️  Model download failed (file empty or not created)"
            fi
          else
            echo "⚠️  Failed to download model from GitHub"
            echo "  URL: $GITHUB_RAW_URL"
            echo "  Please check that the file is pushed and the repo is public"
          fi

          echo ""

          # List created structure
          echo "Current MinIO structure:"
          mc ls myminio/models/model/yolo11n/
          mc ls myminio/models/model/yolo11n/1/ 2>/dev/null || echo "  (version 1 directory will be created when model is uploaded)"
          echo ""

          echo "========================================"
          echo "MinIO Initialization Complete!"
          echo "========================================"
          echo ""
          echo "Next steps:"
          echo "  1. Model should be automatically loaded from GitHub"
          echo "  2. If not, check that models/yolo11n.onnx is pushed to the repo"
          echo "  3. Or upload manually via MinIO Console"
          echo ""
