apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: train-detection
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Optional: Specify storage class
  # storageClassName: gp2
