apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  # MinIO root credentials
  # Change these values before deploying!
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "ChangeMe123!"

  # Optional: AWS-compatible credentials for clients
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "ChangeMe123!"
