apiVersion: v1
kind: Secret
metadata:
  name: storage-config
  namespace: train-detection
  annotations:
    serving.kserve.io/s3-endpoint: minio:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-verifyssl: "0"
    serving.kserve.io/s3-region: us-east-1
type: Opaque
stringData:
  # MinIO S3 credentials
  # CHANGE THESE to match your MinIO credentials from minio/secret.yaml!
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "ChangeMe123!"
