apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: yolo11-triton-runtime
  namespace: train-detection
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    description: "Triton Inference Server runtime for YOLOv11 ONNX models"
spec:
  supportedModelFormats:
    - name: onnx
      version: "1"
      autoSelect: true
  multiModel: false
  containers:
    - name: triton
      image: nvcr.io/nvidia/tritonserver:24.01-py3
      args:
        - tritonserver
        - --model-store=/mnt/models
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
        - --model-control-mode=explicit
      ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        - containerPort: 9000
          protocol: TCP
          name: grpc
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      livenessProbe:
        httpGet:
          path: /v2/health/live
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /v2/health/ready
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
  protocolVersions:
    - v2
    - grpc-v2
  grpcEndpoint: "port:9000"
  grpcDataEndpoint: "port:9001"
