apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: yolo11-triton-runtime
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    openshift.io/display-name: "Triton Runtime for YOLOv11"
    opendatahub.io/template-name: "triton-yolo11"
    opendatahub.io/template-display-name: "Triton Runtime for YOLOv11"
    opendatahub.io/apiProtocol: "REST"
    opendatahub.io/modelServingSupport: '["single"]'
    enable: "true"
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8002"
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8002"
  supportedModelFormats:
    - autoSelect: true
      name: onnx
      version: "1"
    - autoSelect: true
      name: tensorrt
      version: "8"
    - autoSelect: true
      name: tensorflow
      version: "1"
    - autoSelect: true
      name: tensorflow
      version: "2"
    - name: pytorch
      version: "1"
    - autoSelect: true
      name: triton
      version: "2"
    - autoSelect: true
      name: python
      version: "1"
  multiModel: false
  containers:
    - name: kserve-container
      image: nvcr.io/nvidia/tritonserver:24.09-py3
      args:
        - tritonserver
        - --model-store=/mnt/models
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
        - --model-control-mode=explicit
      ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        - containerPort: 9000
          protocol: TCP
          name: grpc
        - containerPort: 8002
          protocol: TCP
          name: metrics
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      livenessProbe:
        httpGet:
          path: /v2/health/live
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /v2/health/ready
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
  protocolVersions:
    - v2
    - grpc-v2
  grpcEndpoint: "port:9000"
  grpcDataEndpoint: "port:9001"
